apiVersion: v1
kind: Secret
metadata:
  name: netmaker-secret
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if not .Values.postgresql.auth.existingSecret }}
  SQL_PASS: {{ include "netmaker.database.password" . | b64enc }}
  {{- end }}
  {{- if not .Values.mq.existingSecret }}
  MQ_ADMIN_PASSWORD: {{ .Values.mq.password | b64enc }}
  MQ_PASSWORD: {{ .Values.mq.password | b64enc }}
  {{- end }}
  MASTER_KEY: {{ include "netmaker.masterKey" . | b64enc }}
